name: Checkov

on:
  workflow_call:

jobs:
  checkov:
    name: "Checkov"
    runs-on: ubuntu-latest

    permissions:
        contents: read
        security-events: write
        actions: read
        
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Checkov IaC
        uses: bridgecrewio/checkov-action@197d53917e0ff43d63111c0808e40b1aaf28ec1c # v12.3068.0
        with:
          directory: .
          framework: terraform
          hard_fail_on: CRITICAL
          skip_check: CKV_TF_1
          output_format: sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
          category: checkov
