name: Docker

on:
  workflow_call:
    inputs:
      image_name:
        description: "Image name to use for Docker build"
        required: true
        type: string
      # Optional Inputs
      node_version:
        description: "Node version to use for Docker"
        required: false
        type: number
        default: 22
      platforms:
        description: "Platforms to build for"
        required: false
        type: string
        default: "linux/arm64, linux/amd64"

# OIDC Token permissions & GitHub Packages permissions
permissions:
    id-token: write
    contents: read
    packages: write


jobs:
  ghcr:
    name: GHCR
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: ${{ inputs.node_version }}
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{raw}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 #v3.11.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GHCR
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6.18.0
        with:
          context: .
          push: true
          platforms: ${{ inputs.platforms}}
          build-args: |
            NODE_VERSION=${{ env.NODE_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}